<?xml version="1.0" encoding="utf-8"?>
<Project>
  <ItemGroup>
    <!-- Build -->
    <PackageVersion Include="StyleCop.Analyzers" Version="1.2.0-beta.556" />
    <PackageVersion Include="JetBrains.Annotations" Version="2025.2.4" />

    <!-- Libraries -->
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.12" />
    <PackageVersion Include="Microsoft.IO.RecyclableMemoryStream" Version="3.0.1" />
    <PackageVersion Include="Scrutor" Version="7.0.0" />
    <PackageVersion Include="AWSSDK.S3" Version="4.0.104.1" />

    <!-- Tests -->
    <PackageVersion Include="FluentFTP" Version="55.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
    <PackageVersion Include="Meziantou.Extensions.Logging.Xunit.v3" Version="3.0.8" />
  </ItemGroup>
</Project>
