<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Interfaces for the portable FTP server</Description>
    <RootNamespace>FubarDev.FtpServer</RootNamespace>
    <PackageTags>portable;FTP;server</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <!-- Provides IFeatureCollection (Http.Features), Options, Logging and Pipelines -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="JetBrains.Annotations" PrivateAssets="All" />
  </ItemGroup>
  <Import Project="..\FubarDev.FtpServer.Shared\FubarDev.FtpServer.Shared.projitems" Label="Shared" />
</Project>
