<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>In-memory file system for portable FTP server</Description>
    <PackageTags>file;system;portable;FTP;server</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FubarDev.FtpServer.Abstractions\FubarDev.FtpServer.Abstractions.csproj" />
  </ItemGroup>
</Project>
